project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
  
execute:
  freeze: auto
  cache: true

website:
  title: "Advanced Microeconomics"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus.qmd
      - text: "Content"
        file: content/lecture1.qmd
      - text: "Practice"
        file: practice.qmd
      - icon: github
        href: https://divbhagia.github.io/econ502/

  sidebar:
    - title: "Lectures"
      style: "docked"
      search: false
      contents:
      - section: "I. Competitive Markets"
        contents:
          - text: "1. Consumer Preferences and Choice"
            file: content/lecture1.qmd
          - text: "2. Demand Analysis and Consumer Welfare"
            file: content/lecture2.qmd
          - text: "3. Production, Costs, and Firm Supply"
            file: content/lecture3.qmd
          - text: "4. Competitive Market Equilibrium"
            file: content/lecture4.qmd
          - text: "5. Welfare Analysis and Efficiency"
            file: content/lecture5.qmd
          - text: "Additional Content"
            file: content/part1-add-content.qmd
      - section: "II. Market Power"
        contents:
          - text: "6. Market Power in Goods Markets"
            file: content/lecture6.qmd
          - text: "7. Market Power in Goods Markets (cont.)"
            file: content/lecture7.qmd
          - text: "Additional Content"
            file: content/part2-add-content.qmd
      - section: "III. Market Failures"
        contents:
          - text: "8. Asymmetric Information"
            file: content/lecture8.qmd
          - text: "9. Externalities and Public Goods"
            file: content/lecture9.qmd
          - text: "Additional Content"
            file: content/part3-add-content.qmd
      - section: "IV. Introduction to Game Theory"
        contents:
          - text: "10. Introduction to Game Theory"
            file: content/lecture10.qmd
          - text: "Additional Content"
            file: content/part4-add-content.qmd
    
  
  page-footer:
      2026 Div Bhagia | [CC BY-NC 4.0 License](https://creativecommons.org/licenses/by-nc/4.0/) |Made with [Quarto](https://quarto.org/)

format:
  html:
    theme: assets/website.scss
    toc: true
    link-external-newwindow: true
    css: assets/styles.css
  revealjs:
    embed-resources: true
    pdf-separate-fragments: false
    navigation-mode: linear
    hash-type: number
    slide-number: true
    controls: true
    progress: true
    transition: fade
    transition-speed: fast
    center: false
    code-overflow: wrap
    highlight-style: a11y-dark
    chalkboard: false
    mathjax: true
    mathjax-config:
      output:
        font: mathjax-tex
      tex:
        packages: {'[+]': ['ams']}