project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
  
execute:
  freeze: auto
  cache: true

website:
  title: "Advanced Microeconomics"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus.qmd
      - text: "Content"
        file: content/lecture1.qmd
      - icon: github
        href: https://divbhagia.github.io/econ502/

  sidebar:
    - title: "Lectures"
      style: "docked"
      search: false
      contents:
      - section: "Part I"
        contents:
          - text: "Lecture 1"
            file: content/lecture1.qmd
  
  page-footer:
      2026 Div Bhagia | [CC BY-NC 4.0 License](https://creativecommons.org/licenses/by-nc/4.0/) |Made with [Quarto](https://quarto.org/)

format:
  html:
    theme: assets/website.scss
    toc: true
    link-external-newwindow: true
    css: assets/styles.css
  revealjs:
    embed-resources: true
    pdf-separate-fragments: false
    navigation-mode: linear
    hash-type: number
    slide-number: true
    controls: true
    progress: true
    transition: fade
    transition-speed: fast
    center: false
    code-overflow: wrap
    highlight-style: a11y-dark
    chalkboard: false
    mathjax: true
    mathjax-config:
      output:
        font: mathjax-tex
      tex:
        packages: {'[+]': ['ams']}