project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
  
execute:
  freeze: auto
  cache: true

website:
  title: "Advanced Microeconomics"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus.qmd
      - text: "Content"
        file: content/lecture1.qmd
      - text: "Problem Sets"
        file: problem-sets.qmd
      - icon: github
        href: https://divbhagia.github.io/econ502/

  sidebar:
    - title: "Lectures"
      style: "docked"
      search: false
      contents:
      - section: "I. Competitive Markets"
        contents:
          - text: "Lecture 1"
            file: content/lecture1.qmd
          - text: "Lecture 2"
            file: content/lecture2.qmd
          - text: "Lecture 3"
            file: content/lecture3.qmd
          - text: "Lecture 4"
            file: content/lecture4.qmd
          - text: "Lecture 5"
            file: content/lecture5.qmd
          - text: "Additional Handouts"
            file: content/part1-add-handouts.qmd
      - section: "II. Market Power"
        contents:
          - text: "Lecture 6"
            file: content/lecture6.qmd
          - text: "Lecture 7"
            file: content/lecture7.qmd
          - text: "Lecture 8"
            file: content/lecture8.qmd
          - text: "Additional Handouts"
            file: content/part2-add-handouts.qmd
      - section: "III. Market Failures"
        contents:
          - text: "Lecture 9"
            file: content/lecture9.qmd
          - text: "Lecture 10"
            file: content/lecture10.qmd
          - text: "Additional Handouts"
            file: content/part3-add-handouts.qmd
      - section: "IV. Uncertainty and Strategy"
        contents:
          - text: "Lecture 11"
            file: content/lecture11.qmd
          - text: "Lecture 12"
            file: content/lecture12.qmd
          - text: "Additional Handouts"
            file: content/part4-add-handouts.qmd
    
  
  page-footer:
      2026 Div Bhagia | [CC BY-NC 4.0 License](https://creativecommons.org/licenses/by-nc/4.0/) |Made with [Quarto](https://quarto.org/)

format:
  html:
    theme: assets/website.scss
    toc: true
    link-external-newwindow: true
    css: assets/styles.css
  revealjs:
    embed-resources: true
    pdf-separate-fragments: false
    navigation-mode: linear
    hash-type: number
    slide-number: true
    controls: true
    progress: true
    transition: fade
    transition-speed: fast
    center: false
    code-overflow: wrap
    highlight-style: a11y-dark
    chalkboard: false
    mathjax: true
    mathjax-config:
      output:
        font: mathjax-tex
      tex:
        packages: {'[+]': ['ams']}