format:
  revealjs:
    embed-resources: true
    pdf-separate-fragments: false
    navigation-mode: linear
    hash-type: number
    slide-number: true
    controls: true
    progress: true
    transition: fade
    transition-speed: fast
    center: false
    code-overflow: wrap
    highlight-style: a11y-dark
    chalkboard: false
    mathjax: true
    mathjax-config:
      output:
        font: mathjax-tex
      tex:
        packages: {'[+]': ['ams']}