{
  "hash": "b6d3102ef7344320571bd43fbbb3324f",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Problem Set 2: Solutions\"\nsubtitle: \"Econ 502: Advanced Microeconomics\"\nformat:\n  html: default\n  pdf:\n    documentclass: article\n    geometry: margin=1in\n    fontsize: 11pt\n    include-in-header:\n      file: ../assets/pset-preamble.tex\nformat-links: [pdf]\n---\n\n\n## Problem 1: Automation and Labor Demand\n\n### Part (a): Elasticity of substitution\n\nThe production function \n$$Q = [0.6R^{0.5} + 0.4L^{0.5}]^2$$ is a CES function with parameter $\\rho = 0.5$ (since the outer exponent is $1/\\rho = 2$). The elasticity of substitution is:\n\n$$\\sigma = \\frac{1}{1 - \\rho} = \\frac{1}{1 - 0.5} = 2$$\n\nSince $\\sigma = 2 > 1$, robots and workers are **good substitutes**: more substitutable than Cobb-Douglas ($\\sigma = 1$). The firm can replace workers with robots relatively easily when the price of robots falls. A 1% decrease in the relative price of robots leads to a 2% increase in the robot-to-worker ratio. For more details on CES functions, see handout [here](/add-content/lec3-ces-prod-func.qmd). \n\n\n### Part (b): Cost-minimizing input mix for $Q = 1000$\n\nThe cost-minimizing condition requires $MRTS = r/w$. Computing the marginal products:\n\n$$MP_R = 2[0.6R^{0.5} + 0.4L^{0.5}] \\cdot 0.3 R^{-0.5}, \\qquad MP_L = 2[0.6R^{0.5} + 0.4L^{0.5}] \\cdot 0.2 L^{-0.5}$$\n\nTaking the ratio:\n\n$$MRTS = \\frac{MP_R}{MP_L} = \\frac{0.3}{0.2} \\cdot \\frac{L^{0.5}}{R^{0.5}} = 1.5\\left(\\frac{L}{R}\\right)^{0.5}$$\n\nSetting $MRTS = r/w$ and solving for the input ratio:\n\n$$1.5\\left(\\frac{L}{R}\\right)^{0.5} = \\frac{r}{w} \\quad \\Longrightarrow \\quad \\frac{R}{L} = \\left(\\frac{1.5w}{r}\\right)^2$$\n\nWith $r = 20$ and $w = 25$:\n\n$$\\frac{R}{L} = \\left(\\frac{1.5 \\times 25}{20}\\right)^2 = (1.875)^2 \\approx 3.52$$\n\nSo $R \\approx 3.52L$. Substituting into the production function with $Q = 1000$:\n\n$$\\sqrt{1000} = 0.6\\sqrt{3.52}\\,L^{0.5} + 0.4\\,L^{0.5} = L^{0.5}(0.6 \\times 1.876 + 0.4) = 1.526\\,L^{0.5}$$\n\n$$L^{0.5} = \\frac{31.62}{1.526} = 20.72 \\quad \\Longrightarrow \\quad L \\approx 429$$\n\n$$R \\approx 3.52 \\times 429 \\approx 1{,}510$$\n\nTotal cost: $C = 20(1{,}510) + 25(429) = 30{,}200 + 10{,}725 = \\$40{,}925$.\n\n$$\\boxed{R \\approx 1{,}510, \\quad L \\approx 429, \\quad C \\approx \\$40{,}925}$$\n\n\n### Part (c): Robot rental rate falls to $r = 10$\n\nWith the new prices:\n\n$$\\frac{R}{L} = \\left(\\frac{1.5 \\times 25}{10}\\right)^2 = (3.75)^2 = 14.06$$\n\nSo $R \\approx 14.06L$. Substituting into the production constraint:\n\n$$\\sqrt{1000} = L^{0.5}(0.6 \\times 3.75 + 0.4) = 2.65\\,L^{0.5}$$\n\n$$L^{0.5} = 11.93 \\quad \\Longrightarrow \\quad L \\approx 142$$\n\n$$R \\approx 14.06 \\times 142 \\approx 1{,}997$$\n\n**Percentage change in robot-to-worker ratio:** The ratio goes from 3.52 to 14.06, an increase of $\\frac{14.06 - 3.52}{3.52} \\times 100 \\approx 300\\%$. The robot-to-worker ratio **quadruples**. This is because when $r$ halves, the relative price $w/r$ doubles, and with $\\sigma = 2$ the input ratio responds by a factor of $2^2 = 4$.\n\n\n**New cost of production:** $C = 10(1{,}997) + 25(142) = 19{,}970 + 3{,}550 = \\$23{,}520$. The cost of producing 1000 units falls by about 42% due to the cheaper robots.\n\n$$\\boxed{R \\approx 1{,}997, \\quad L \\approx 142, \\quad C \\approx \\$23{,}520}$$\n\n### Part (d): Robot tax and job savings\n\nA robot tax raising $r$ back to 20 would restore the input mix from part (b). Since the firm would use 429 workers instead of 142, the tax would save approximately $287$ worker-hours per 1,000 units of output.\n\n**The trade-off:**  The cost of producing 1000 units would rise by about 42% from \\$23,520 back to \\$40,925, which may lead to higher prices for consumers and lower profits for the firm. The tax protects jobs but at the cost of efficiency and potentially higher prices. The firm may also have less incentive to invest in automation in the future, which could slow technological progress. But do we want to live in a society where people don't have jobs? Maybe if everyone owned robots, we wouldn't have to worry about unemployment. There is also a possibility that new jobs could be created to replace the ones lost to automation.\n\n## Problem 2: Profit Maximization and Taxation\n\nA competitive firm maximizes profit $\\pi = P \\cdot q - C(q)$, yielding the first-order condition $P = MC(q)$.\n\n**Lump-sum tax on profits.** With a lump-sum tax $T$, profit becomes: $$\\pi = Pq - C(q) - T$$ The FOC is still $P = MC(q)$ since $T$ does not depend on the level of output $Q$. The profit-maximizing quantity is **unchanged** as the firm can't change it's tax burden by adjusting output. The lump-sum tax reduces profits but does not distort production decisions.\n\n**Proportional tax on profits.** With tax rate $t$, after-tax profit is: $$\\pi = (1-t)[Pq - C(q)]$$ The FOC now is $(1-t)[P - MC(q)] = 0$, which implies $P = MC(q)$, the same condition as before. Once again, the profit-maximizing quantity is **unchanged**. \n\n**Output tax.** With a per-unit tax $\\tau$, profit becomes: $$\\pi = Pq - C(q) - \\tau q = (P - \\tau)q - C(q)$$ The FOC is $P - \\tau = MC(q)$, so the firm produces where marginal cost equals the net price $P - \\tau$. Since $MC$ is increasing, the profit-maximizing quantity **decreases**. The per-unit tax is equivalent to a reduction in the output price: it shifts the effective price down and reduces output.\n\n**Intuition** for why there is distortion with an output tax but not with a proportional tax: The output tax makes each unit of output less profitable, so the firm produces less. With a proportional tax, the firm still wants to produce the quantity that maximizes pre-tax profits, since a higher pre-tax profit means a higher after-tax profit even after paying the percentage to the government. \n\n**Tax on labor input.** If the firm uses labor $L$ at wage $w$ and the government imposes a tax $t_L$ per unit of labor, the effective wage rises to $w + t_L$. This increases the cost function $C(q)$, which shifts $MC(q)$ upward. Since the firm produces where $P = MC(q)$, a higher $MC$ curve means a lower profit-maximizing quantity. Output **decreases**. The firm also substitutes away from labor toward other inputs.\n\n\n\n\n## Problem 3: Trade Policy and the Portable Radio Market\n\n### Part (a): Domestic equilibrium\n\nSetting domestic demand equal to domestic supply:\n\n$$D(P) = S(P) \\quad \\Longrightarrow \\quad 5{,}000 - 100P = 150P \\quad \\Longrightarrow \\quad 250P = 5{,}000$$\n\n$$\\boxed{P^* = \\$20, \\qquad Q^* = 3{,}000 \\text{ radios}}$$\n\n\n### Part (b): Free trade at world price $P_W = \\$10$\n\nAt $P = 10$:\n\n- Domestic demand: $Q_D = 5{,}000 - 100(10) = 4{,}000$ \n- Domestic supply: $Q_S = 150(10) = 1{,}500$\n\n$$\\boxed{\\text{Imports} = Q_D - Q_S = 4{,}000 - 1{,}500 = 2{,}500 \\text{ radios}}$$\n\nThe price falls from \\$20 to \\$10, domestic consumption rises, domestic production falls, and the gap is filled by imports.\n\n\n### Part (c): \\$5 tariff\n\nWith the tariff, the domestic price rises to $P = 10 + 5 = \\$15$:\n\n- Domestic demand: $Q_D = 5{,}000 - 100(15) = 3{,}500$ \n- Domestic supply: $Q_S = 150(15) = 2{,}250$ \n- Imports: $3{,}500 - 2{,}250 = 1{,}250$ \n\n**Tariff revenue:**\n\n$$R = \\$5 \\times 1{,}250 = \\$6{,}250 $$\n\n**Change in consumer surplus** (A+B+C+D):\n\n$$\\Delta CS = -\\frac{1}{2}(Q_D^{FT} + Q_D^{T})(P^{T} - P^{FT}) = -\\frac{1}{2}(4{,}000 + 3{,}500)(5) = -\\$18{,}750 $$\n\n**Consumer surplus transferred to domestic producers** (D):\n\n$$\\Delta PS = \\frac{1}{2}(Q_S^{FT} + Q_S^{T})(P^{T} - P^{FT}) = \\frac{1}{2}(1{,}500 + 2{,}250)(5) = \\$9{,}375 $$\n\n**Deadweight loss** (A+C):\n\n$$DWL = |\\Delta CS| - \\Delta PS - R = 18{,}750 - 9{,}375 - 6{,}250 = \\$3{,}125 $$\nThis DWL consists of two triangles:\n\n- *Production inefficiency (C)*: $\\frac{1}{2}(5)(2{,}250 - 1{,}500) = 1{,}875$ (resources wasted producing domestically what could be imported more cheaply)\n- *Consumption loss (A)*: $\\frac{1}{2}(5)(4{,}000 - 3{,}500) = 1{,}250$ (lost surplus from consumers priced out of the market)\n\n::: {#84363dcd .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![](ps2-solutions_files/figure-html/cell-2-output-1.png){width=566 height=467 fig-align='center'}\n:::\n:::\n\n\n### Part (d): Voluntary Export Restraint (VER) \n\nWith the VER limiting imports to 1,250, the domestic price must adjust so that $Q_D - Q_S = 1{,}250$:\n\n$$5{,}000 - 100P - 150P = 1{,}250 \\quad \\Longrightarrow \\quad P = \\$15$$\n\nThe equilibrium price, domestic demand, domestic supply, and import quantity are **identical** to the tariff case.\n\n**Key difference:** With a tariff, the government collects \\$6,250 in tariff revenue. With the VER, there is no tariff: foreign exporters sell at the higher domestic price of \\$15 instead of the world price of \\$10, so they capture the \\$6,250 as **quota rents**.\n\nFrom the domestic country's perspective, the VER is strictly worse than the tariff:\n\n| | Tariff | VER |\n|---|---|---|\n| CS loss | -18,750 | -18,750 |\n| PS gain | +9,375 | +9,375 |\n| Gov. revenue | +6,250 | 0 |\n| Quota rents to foreigners | 0 | -6,250 |\n| **Net domestic welfare change** | -**3,125** | -**9,375** |\n\nThe VER transfers an additional \\$6,250 to foreign producers, making the domestic welfare loss three times larger than the tariff.\n\n\n\n\n## Problem 4: General Equilibrium Exchange\n\n### Part (a): MRS at initial endowment\n\nFor $U = X \\cdot Y$ (Cobb-Douglas with equal exponents):\n\n$$MRS = \\frac{MU_X}{MU_Y} = \\frac{Y}{X}$$\n\nAt the initial endowment $(X_A, Y_A) = (70, 30)$ and $(X_B, Y_B) = (30, 70)$:\n\n$$MRS_A = \\frac{30}{70} = \\frac{3}{7} \\approx 0.43, \\qquad MRS_B = \\frac{70}{30} = \\frac{7}{3} \\approx 2.33$$\n\nSince $MRS_A \\neq MRS_B$, the initial allocation is **not Pareto efficient**. There are gains from trade: Ben values X much more highly than Ana does (he is willing to give up 7/3 units of Y for one unit of X, while Ana would only give up 3/7). Ana should trade X to Ben in exchange for Y.\n\n\n### Part (b): Competitive equilibrium at $P_X/P_Y = 1$\n\nLet $P_Y = 1$ (numeraire), so $P_X = 1$.\n\n**Ana's problem:** Budget $= P_X \\cdot 70 + P_Y \\cdot 30 = 100$. With $U = XY$, the demand functions are:\n\n$$X_A = \\frac{I_A}{2P_X} = \\frac{100}{2} = 50, \\qquad Y_A = \\frac{I_A}{2P_Y} = \\frac{100}{2} = 50$$\n\n**Ben's problem:** Budget $= P_X \\cdot 30 + P_Y \\cdot 70 = 100$. By the same logic:\n\n$$X_B = \\frac{100}{2} = 50, \\qquad Y_B = \\frac{100}{2} = 50$$\n\n**Market clearing:** Total demand for $X$: $50 + 50 = 100$ = total endowment. ✓\n\n$$\\boxed{(X_A, Y_A) = (50, 50), \\qquad (X_B, Y_B) = (50, 50)}$$\n\nAna trades 20 units of X to Ben in exchange for 20 units of Y.\n\n\n### Part (c): Verifying Pareto efficiency\n\nAt the equilibrium allocation:\n\n$$MRS_A = \\frac{Y_A}{X_A} = \\frac{50}{50} = 1, \\qquad MRS_B = \\frac{Y_B}{X_B} = \\frac{50}{50} = 1$$\n\n$$\\boxed{MRS_A = MRS_B = 1 = \\frac{P_X}{P_Y}}$$\n\nThe competitive equilibrium is Pareto efficient: both consumers' marginal rates of substitution are equal (to each other and to the price ratio), so there is no way to make one person better off without making the other worse off.\n\n\n### Part (d): Contract curve and the First Welfare Theorem\n\nThe **contract curve** is the set of all Pareto efficient allocations, where $MRS_A = MRS_B$:\n\n$$\\frac{Y_A}{X_A} = \\frac{Y_B}{X_B} = \\frac{100 - Y_A}{100 - X_A}$$\n\nCross-multiplying: $Y_A(100 - X_A) = X_A(100 - Y_A)$, which simplifies to:\n\n$$\\boxed{Y_A = X_A}$$\n\nThe contract curve is the diagonal of the Edgeworth box (equivalently, $Y_B = X_B$). Every Pareto efficient allocation gives each person equal amounts of both goods.\n\nThe **First Welfare Theorem** states that every competitive equilibrium allocation is Pareto efficient. We verified this in part (c): the equilibrium allocation $(50, 50)$ for both consumers lies on the contract curve ($Y_A = X_A = 50$). The competitive market, guided only by prices, achieves an efficient outcome without any central planner.\n\n\n\n\n## Problem 5: Optimal Redistribution with Distortionary Taxation\n\n### Part (a): Deriving the optimal tax rate\n\nSubstituting the consumption expressions into the welfare function:\n\n$$c_P = y_P + \\tau y_R - \\frac{1}{2}k\\tau^2 y_R, \\qquad c_R = (1-\\tau)y_R$$\n\n$$W(\\tau) = \\alpha\\left[y_P + \\tau y_R - \\frac{1}{2}k\\tau^2 y_R\\right] + (1-\\alpha)(1-\\tau)y_R$$\n\nExpanding:\n\n$$W(\\tau) = \\alpha y_P + \\alpha\\tau y_R - \\frac{1}{2}\\alpha k\\tau^2 y_R + (1-\\alpha)y_R - (1-\\alpha)\\tau y_R$$\n\nTaking the first-order condition:\n\n$$\\frac{dW}{d\\tau} = \\alpha y_R - \\alpha k\\tau y_R - (1-\\alpha)y_R = 0$$\n\nDividing through by $y_R$:\n\n$$\\alpha - \\alpha k\\tau - (1 - \\alpha) = 0$$\n\n$$2\\alpha - 1 = \\alpha k\\tau$$\n\n$$\\boxed{\\tau^* = \\frac{2\\alpha - 1}{\\alpha k}}$$\n\nThe second-order condition confirms this is a maximum: $\\frac{d^2W}{d\\tau^2} = -\\alpha k y_R < 0$. Note that $\\tau^* > 0$ requires $\\alpha > 1/2$: positive redistribution is only optimal when society places more weight on the poor than on the rich.\n\n\n### Part (b): Comparative statics\n\nRewriting $\\tau^*$ in a more convenient form:\n\n$$\\tau^* = \\frac{2}{k} - \\frac{1}{\\alpha k}$$\n\n**(i) Effect of inequality aversion $\\alpha$:**\n\n$$\\frac{\\partial \\tau^*}{\\partial \\alpha} = \\frac{1}{\\alpha^2 k} > 0$$\n\nHigher inequality aversion (larger $\\alpha$) increases the optimal tax rate. **Intuition:** When society cares more about the well-being of the poor relative to the rich, it is willing to tolerate more deadweight loss in order to transfer additional resources to the poor. A more egalitarian social welfare function justifies a larger tax-and-transfer program.\n\n**(ii) Effect of the distortion parameter $k$:**\n\n$$\\frac{\\partial \\tau^*}{\\partial k} = -\\frac{2\\alpha - 1}{\\alpha k^2} < 0 \\quad \\text{(for } \\alpha > 1/2\\text{)}$$\n\nA higher distortion cost (larger $k$) decreases the optimal tax rate. \n**Intuition:** When taxation is more distortionary (meaning more revenue is lost to deadweight loss per dollar collected), the government should tax less aggressively. The \"leaky bucket\" of redistribution becomes leakier: each dollar taken from the rich delivers less than a dollar to the poor, so the marginal cost of redistribution rises and the optimal level falls.\n\n",
    "supporting": [
      "ps2-solutions_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}