<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Part 3: Market Failures Practice Problem Solutions – Advanced Microeconomics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-6633c62d358394232bc599d39e38c5c9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-40de7c3d014d17db877f778cb01e6f5d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Advanced Microeconomics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../content/lecture1.html"> 
<span class="menu-text">Content</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../practice.html"> 
<span class="menu-text">Practice</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://divbhagia.github.io/econ502/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#problem-1-adverse-selection-in-insurance" id="toc-problem-1-adverse-selection-in-insurance" class="nav-link active" data-scroll-target="#problem-1-adverse-selection-in-insurance">Problem 1: Adverse Selection in Insurance</a>
  <ul class="collapse">
  <li><a href="#part-a-certainty-equivalent-and-maximum-premium" id="toc-part-a-certainty-equivalent-and-maximum-premium" class="nav-link" data-scroll-target="#part-a-certainty-equivalent-and-maximum-premium">Part (a): Certainty equivalent and maximum premium</a></li>
  <li><a href="#part-b-pooled-premium-at-lambda-0.5" id="toc-part-b-pooled-premium-at-lambda-0.5" class="nav-link" data-scroll-target="#part-b-pooled-premium-at-lambda-0.5">Part (b): Pooled premium at <span class="math inline">\(\lambda = 0.5\)</span></a></li>
  <li><a href="#part-c-range-of-lambda-for-unraveling" id="toc-part-c-range-of-lambda-for-unraveling" class="nav-link" data-scroll-target="#part-c-range-of-lambda-for-unraveling">Part (c): Range of <span class="math inline">\(\lambda\)</span> for unraveling</a></li>
  <li><a href="#part-d-compulsory-insurance-at-p_textpool-14.40" id="toc-part-d-compulsory-insurance-at-p_textpool-14.40" class="nav-link" data-scroll-target="#part-d-compulsory-insurance-at-p_textpool-14.40">Part (d): Compulsory insurance at <span class="math inline">\(P_{\text{pool}} = 14.40\)</span></a></li>
  </ul></li>
  <li><a href="#problem-2-pigouvian-tax-and-cap-and-trade" id="toc-problem-2-pigouvian-tax-and-cap-and-trade" class="nav-link" data-scroll-target="#problem-2-pigouvian-tax-and-cap-and-trade">Problem 2: Pigouvian Tax and Cap-and-Trade</a>
  <ul class="collapse">
  <li><a href="#part-a-unregulated-equilibrium" id="toc-part-a-unregulated-equilibrium" class="nav-link" data-scroll-target="#part-a-unregulated-equilibrium">Part (a): Unregulated equilibrium</a></li>
  <li><a href="#part-b-socially-efficient-outcome" id="toc-part-b-socially-efficient-outcome" class="nav-link" data-scroll-target="#part-b-socially-efficient-outcome">Part (b): Socially efficient outcome</a></li>
  <li><a href="#part-c-pigouvian-tax" id="toc-part-c-pigouvian-tax" class="nav-link" data-scroll-target="#part-c-pigouvian-tax">Part (c): Pigouvian tax</a></li>
  <li><a href="#part-d-cap-and-trade" id="toc-part-d-cap-and-trade" class="nav-link" data-scroll-target="#part-d-cap-and-trade">Part (d): Cap-and-trade</a></li>
  </ul></li>
  <li><a href="#problem-3-coase-theorem" id="toc-problem-3-coase-theorem" class="nav-link" data-scroll-target="#problem-3-coase-theorem">Problem 3: Coase Theorem</a>
  <ul class="collapse">
  <li><a href="#part-a-total-surplus" id="toc-part-a-total-surplus" class="nav-link" data-scroll-target="#part-a-total-surplus">Part (a): Total surplus</a></li>
  <li><a href="#part-b-doctor-has-the-right-to-silence" id="toc-part-b-doctor-has-the-right-to-silence" class="nav-link" data-scroll-target="#part-b-doctor-has-the-right-to-silence">Part (b): Doctor has the right to silence</a></li>
  <li><a href="#part-c-bakery-has-the-right-to-be-noisy" id="toc-part-c-bakery-has-the-right-to-be-noisy" class="nav-link" data-scroll-target="#part-c-bakery-has-the-right-to-be-noisy">Part (c): Bakery has the right to be noisy</a></li>
  <li><a href="#part-d-comparison-and-the-coase-theorem" id="toc-part-d-comparison-and-the-coase-theorem" class="nav-link" data-scroll-target="#part-d-comparison-and-the-coase-theorem">Part (d): Comparison and the Coase theorem</a></li>
  </ul></li>
  <li><a href="#problem-4-public-good-provision" id="toc-problem-4-public-good-provision" class="nav-link" data-scroll-target="#problem-4-public-good-provision">Problem 4: Public Good Provision</a>
  <ul class="collapse">
  <li><a href="#part-a-best-response-and-nash-equilibrium" id="toc-part-a-best-response-and-nash-equilibrium" class="nav-link" data-scroll-target="#part-a-best-response-and-nash-equilibrium">Part (a): Best response and Nash equilibrium</a></li>
  <li><a href="#part-b-social-optimum" id="toc-part-b-social-optimum" class="nav-link" data-scroll-target="#part-b-social-optimum">Part (b): Social optimum</a></li>
  <li><a href="#part-c-samuelson-and-the-free-rider-gap" id="toc-part-c-samuelson-and-the-free-rider-gap" class="nav-link" data-scroll-target="#part-c-samuelson-and-the-free-rider-gap">Part (c): Samuelson and the free-rider gap</a></li>
  <li><a href="#part-d-pigouvian-style-subsidy" id="toc-part-d-pigouvian-style-subsidy" class="nav-link" data-scroll-target="#part-d-pigouvian-style-subsidy">Part (d): Pigouvian-style subsidy</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="part3-add-solutions.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Part 3: Market Failures Practice Problem Solutions</h1>
<p class="subtitle lead">Econ 502: Advanced Microeconomics</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="problem-1-adverse-selection-in-insurance" class="level2">
<h2 class="anchored" data-anchor-id="problem-1-adverse-selection-in-insurance">Problem 1: Adverse Selection in Insurance</h2>
<section id="part-a-certainty-equivalent-and-maximum-premium" class="level3">
<h3 class="anchored" data-anchor-id="part-a-certainty-equivalent-and-maximum-premium">Part (a): Certainty equivalent and maximum premium</h3>
<p>Without insurance, expected utility for a type-<span class="math inline">\(i\)</span> consumer is</p>
<p><span class="math display">\[EU_i = (1-p_i)\sqrt{w} + p_i \sqrt{w - L} = (1-p_i)(10) + p_i(8) = 10 - 2 p_i\]</span></p>
<p>The <strong>certainty equivalent</strong> <span class="math inline">\(CE_i\)</span> is the certain wealth that yields the same utility as the gamble:</p>
<p><span class="math display">\[u(CE_i) = EU_i \;\;\Longrightarrow\;\; \sqrt{CE_i} = 10 - 2p_i \;\;\Longrightarrow\;\; CE_i = (10 - 2 p_i)^2\]</span></p>
<p>Plugging in:</p>
<p><span class="math display">\[CE_L = (9.6)^2 = 92.16, \qquad CE_H = (8.8)^2 = 77.44\]</span></p>
<p>The consumer is indifferent between full insurance at premium <span class="math inline">\(P_i^{\max}\)</span> and going uninsured when <span class="math inline">\(u(w - P_i^{\max}) = EU_i\)</span>, i.e., <span class="math inline">\(w - P_i^{\max} = CE_i\)</span>:</p>
<p><span class="math display">\[\boxed{P_i^{\max} = w - CE_i}\]</span></p>
<p><span class="math display">\[P_L^{\max} = 100 - 92.16 = 7.84, \qquad P_H^{\max} = 100 - 77.44 = 22.56\]</span></p>
<p>Verification: <span class="math inline">\(P_H^{\max} = 22.56 &gt; 7.84 = P_L^{\max}\)</span>. <span class="math inline">\(\checkmark\)</span></p>
<p>Note that each willingness-to-pay exceeds the corresponding actuarially fair premium <span class="math inline">\(p_i L\)</span> (<span class="math inline">\(p_L L = 7.20\)</span>, <span class="math inline">\(p_H L = 21.60\)</span>). The gap is the <strong>risk premium</strong> - the extra amount the risk-averse consumer is willing to pay above the expected loss to avoid the gamble.</p>
</section>
<section id="part-b-pooled-premium-at-lambda-0.5" class="level3">
<h3 class="anchored" data-anchor-id="part-b-pooled-premium-at-lambda-0.5">Part (b): Pooled premium at <span class="math inline">\(\lambda = 0.5\)</span></h3>
<p><span class="math display">\[P_{\text{pool}} = (0.5 \cdot 0.6 + 0.5 \cdot 0.2) \cdot 36 = 0.4 \cdot 36 = 14.40\]</span></p>
<ul>
<li><strong>Low-risk:</strong> <span class="math inline">\(P_L^{\max} = 7.84 &lt; 14.40\)</span>. They will <strong>not</strong> buy.</li>
<li><strong>High-risk:</strong> <span class="math inline">\(P_H^{\max} = 22.56 &gt; 14.40\)</span>. They <strong>will</strong> buy.</li>
</ul>
<p>If only high-risk types buy, the insurer’s expected payout per policy is <span class="math inline">\(p_H \cdot L = 21.60\)</span>, but it collects only <span class="math inline">\(14.40\)</span> per policy. The insurer <strong>loses $7.20 per policy</strong> and does not break even.</p>
</section>
<section id="part-c-range-of-lambda-for-unraveling" class="level3">
<h3 class="anchored" data-anchor-id="part-c-range-of-lambda-for-unraveling">Part (c): Range of <span class="math inline">\(\lambda\)</span> for unraveling</h3>
<p>The pooled premium as a function of the high-risk share is</p>
<p><span class="math display">\[P_{\text{pool}}(\lambda) = (0.4 \lambda + 0.2) \cdot 36 = 14.4 \lambda + 7.2\]</span></p>
<p>Low-risk types drop out when <span class="math inline">\(P_{\text{pool}}(\lambda) &gt; P_L^{\max}\)</span>:</p>
<p><span class="math display">\[14.4 \lambda + 7.2 &gt; 7.84 \;\;\Longrightarrow\;\; \lambda &gt; \frac{0.64}{14.4} = \frac{2}{45} \approx 0.044\]</span></p>
<p><span class="math display">\[\boxed{\text{Market unravels for } \lambda &gt; 2/45 \approx 4.4\%}\]</span></p>
<p><strong>Logic.</strong> At the pooled premium, low-risk types subsidize high-risk types. The maximum subsidy a low-risk type tolerates equals their risk premium (<span class="math inline">\(P_L^{\max} - p_L L = 0.64\)</span>). As soon as the pool contains enough high-risk types to push the pooled premium above <span class="math inline">\(P_L^{\max}\)</span>, low-risk consumers prefer to self-insure. Their exit raises the average risk in the pool, forcing the premium even higher - the classic adverse-selection death spiral. With only two types here, the dynamic stops once all low-risk are out and only high-risk remain (paying near <span class="math inline">\(p_H L\)</span>).</p>
</section>
<section id="part-d-compulsory-insurance-at-p_textpool-14.40" class="level3">
<h3 class="anchored" data-anchor-id="part-d-compulsory-insurance-at-p_textpool-14.40">Part (d): Compulsory insurance at <span class="math inline">\(P_{\text{pool}} = 14.40\)</span></h3>
<p>Wealth under insurance is <span class="math inline">\(w - P_{\text{pool}} = 85.60\)</span> in both states, giving utility <span class="math inline">\(\sqrt{85.60} \approx 9.252\)</span>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Type</th>
<th style="text-align: center;"><span class="math inline">\(EU\)</span> no insurance</th>
<th style="text-align: center;"><span class="math inline">\(u\)</span> with mandate</th>
<th style="text-align: center;">Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Low-risk</td>
<td style="text-align: center;"><span class="math inline">\(9.600\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9.252\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-0.348\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">High-risk</td>
<td style="text-align: center;"><span class="math inline">\(8.800\)</span></td>
<td style="text-align: center;"><span class="math inline">\(9.252\)</span></td>
<td style="text-align: center;"><span class="math inline">\(+0.452\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Low-risk are worse off</strong> (forced to subsidize the bad pool).</li>
<li><strong>High-risk are better off</strong> (get coverage at a price below their willingness to pay).</li>
</ul>
<p>The insurer collects <span class="math inline">\(14.40\)</span> per policy and pays out <span class="math inline">\(0.5(0.6) + 0.5(0.2) = 0.4\)</span> in probability <span class="math inline">\(\times\)</span> <span class="math inline">\(L = 36\)</span> on average <span class="math inline">\(= 14.40\)</span>, so it <strong>breaks even</strong>.</p>
<p><strong>Why the policy can still be desirable.</strong> A utilitarian planner adds the changes: net gain <span class="math inline">\(= -0.348 + 0.452 = +0.104\)</span> utils per person - total welfare rises. More fundamentally, the mandate solves the adverse-selection failure: high-risk types receive coverage they could otherwise obtain only at much higher prices, while low-risk types lose only their small risk-aversion benefit. There are also equity arguments: people generally do not choose their risk type, and pooling spreads the cost of bad luck. This logic underlies, e.g., the individual mandate in the Affordable Care Act.</p>
<hr>
</section>
</section>
<section id="problem-2-pigouvian-tax-and-cap-and-trade" class="level2">
<h2 class="anchored" data-anchor-id="problem-2-pigouvian-tax-and-cap-and-trade">Problem 2: Pigouvian Tax and Cap-and-Trade</h2>
<section id="part-a-unregulated-equilibrium" class="level3">
<h3 class="anchored" data-anchor-id="part-a-unregulated-equilibrium">Part (a): Unregulated equilibrium</h3>
<p>Each plant ignores pollution damage and maximizes <span class="math inline">\(y_i (P - c) = 2 y_i\)</span> subject to <span class="math inline">\(y_i \leq 250\)</span>. The per-gallon profit is positive, so each plant produces at capacity:</p>
<p><span class="math display">\[y_1 = y_2 = 250\]</span></p>
<p>Total smog: <span class="math inline">\(s_1 + s_2 = 250^2 + \tfrac{1}{2}(250^2) = 62{,}500 + 31{,}250 = 93{,}750\)</span> cubic feet.</p>
<p><span class="math display">\[\boxed{\text{Total damage} = 0.01 \times 93{,}750 = \$937.50}\]</span></p>
</section>
<section id="part-b-socially-efficient-outcome" class="level3">
<h3 class="anchored" data-anchor-id="part-b-socially-efficient-outcome">Part (b): Socially efficient outcome</h3>
<p>The planner internalizes the damage. Each plant’s social objective is</p>
<p><span class="math display">\[\max_{y_i} \; (P - c) y_i - 0.01 \cdot s_i(y_i)\]</span></p>
<p><strong>Plant 1:</strong> <span class="math inline">\(\max\, 2 y_1 - 0.01 y_1^2\)</span>. FOC: <span class="math inline">\(2 = 0.02 y_1 \Longrightarrow y_1^{*} = 100\)</span>.</p>
<p><strong>Plant 2:</strong> <span class="math inline">\(\max\, 2 y_2 - 0.005 y_2^2\)</span>. FOC: <span class="math inline">\(2 = 0.01 y_2 \Longrightarrow y_2^{*} = 200\)</span>.</p>
<p>Both interior (under capacity 250). The dirtier plant (Plant 1) is cut back more - exactly the asymmetric reallocation that command-and-control with a uniform cap would miss.</p>
<p>Total smog at the efficient outcome: <span class="math display">\[s_1^{*} + s_2^{*} = 100^2 + \tfrac{1}{2}(200^2) = 10{,}000 + 20{,}000 = 30{,}000 \text{ cubic feet}\]</span></p>
<p><span class="math display">\[\boxed{y_1^{*} = 100, \;\; y_2^{*} = 200, \;\; \text{total smog} = 30{,}000}\]</span></p>
</section>
<section id="part-c-pigouvian-tax" class="level3">
<h3 class="anchored" data-anchor-id="part-c-pigouvian-tax">Part (c): Pigouvian tax</h3>
<p>With tax <span class="math inline">\(t = 0.01\)</span> per cubic foot of smog, each plant now solves</p>
<p><span class="math display">\[\max_{y_i} \; (P - c) y_i - t \cdot s_i(y_i)\]</span></p>
<p>This is identical to the planner’s problem in part (b), so each plant chooses the efficient output <span class="math inline">\(y_1 = 100\)</span>, <span class="math inline">\(y_2 = 200\)</span>. <span class="math inline">\(\checkmark\)</span></p>
<p>Total tax revenue: <span class="math inline">\(t \times \text{total smog} = 0.01 \times 30{,}000 = \$300\)</span>.</p>
<p>The tax decentralizes the efficient outcome with minimal information: the regulator only needs to know the marginal damage of smog, not each plant’s pollution function.</p>
</section>
<section id="part-d-cap-and-trade" class="level3">
<h3 class="anchored" data-anchor-id="part-d-cap-and-trade">Part (d): Cap-and-trade</h3>
<p>The regulator issues <span class="math inline">\(\bar{S} = 30{,}000\)</span> permits. Plant <span class="math inline">\(i\)</span> holds initial allocation <span class="math inline">\(e_i\)</span> (with <span class="math inline">\(e_1 + e_2 = 30{,}000\)</span>) and faces market permit price <span class="math inline">\(\tau\)</span>. Each plant’s profit is</p>
<p><span class="math display">\[\pi_i = (P - c) y_i - \tau \big( s_i(y_i) - e_i \big)\]</span></p>
<p>(the second term is the cost of using <span class="math inline">\(s_i\)</span> permits on top of its endowment <span class="math inline">\(e_i\)</span> - negative if the plant ends up a seller). The FOC is the same as under the tax: <span class="math inline">\(P - c = \tau \cdot s_i^{\prime}(y_i)\)</span>, so</p>
<p><span class="math display">\[2 = 2 \tau y_1 \Longrightarrow y_1 = \frac{1}{\tau}, \qquad 2 = \tau y_2 \Longrightarrow y_2 = \frac{2}{\tau}\]</span></p>
<p><strong>Market clearing.</strong> Total permit demand equals supply:</p>
<p><span class="math display">\[y_1^2 + \tfrac{1}{2} y_2^2 = \frac{1}{\tau^2} + \frac{2}{\tau^2} = \frac{3}{\tau^2} = 30{,}000\]</span></p>
<p><span class="math display">\[\tau^{*2} = \frac{1}{10{,}000} \;\;\Longrightarrow\;\; \tau^{*} = \$0.01\]</span></p>
<p>Plugging in: <span class="math inline">\(y_1 = 100\)</span>, <span class="math inline">\(y_2 = 200\)</span> - same as the efficient allocation, and <span class="math inline">\(\tau^{*}\)</span> equals the Pigouvian tax rate.</p>
<p><strong>(i) All permits to Plant 1 (<span class="math inline">\(e_1 = 30{,}000\)</span>, <span class="math inline">\(e_2 = 0\)</span>).</strong></p>
<ul>
<li>Plant 1 uses <span class="math inline">\(s_1 = 100^2 = 10{,}000\)</span> permits and <strong>sells the remaining 20{,}000 to Plant 2</strong> at <span class="math inline">\(\tau = 0.01\)</span>.</li>
<li>Plant 1 profit: <span class="math inline">\(\pi_1 = 100(2) - 0.01(10{,}000) + 0.01(30{,}000) = 200 - 100 + 300 = \$400\)</span>.</li>
<li>Plant 2 profit: <span class="math inline">\(\pi_2 = 200(2) - 0.01(20{,}000) + 0 = 400 - 200 = \$200\)</span>.</li>
</ul>
<p><strong>(ii) All permits to Plant 2 (<span class="math inline">\(e_1 = 0\)</span>, <span class="math inline">\(e_2 = 30{,}000\)</span>).</strong></p>
<p>The first-order conditions and market-clearing equation are unchanged, so <span class="math inline">\(\tau^{*} = 0.01\)</span> and <span class="math inline">\(y_1 = 100\)</span>, <span class="math inline">\(y_2 = 200\)</span> as before.</p>
<p>What changes is the trade direction and profits:</p>
<ul>
<li>Plant 2 keeps 20{,}000 permits for its own use and <strong>sells 10{,}000 to Plant 1</strong>.</li>
<li>Plant 1 profit: <span class="math inline">\(\pi_1 = 200 - 100 + 0 = \$100\)</span>.</li>
<li>Plant 2 profit: <span class="math inline">\(\pi_2 = 400 - 200 + 300 = \$500\)</span>.</li>
</ul>
<p>Both plants produce the efficient quantities - only the distribution of profits shifts (totals are <span class="math inline">\(\$600\)</span> in both cases, redistributed by the permit revenue).</p>
<p><strong>(iii) Connection to the Coase theorem.</strong></p>
<p>With well-defined property rights (permits) and frictionless trade, the <strong>efficient allocation arises regardless of who initially holds the rights</strong>. The initial allocation only redistributes surplus; it has no effect on which plant pollutes how much. The regulator does not need to know plants’ cost or pollution functions - the market reveals them through trading.</p>
<p>The price-based (Pigouvian tax) and quantity-based (cap-and-trade) instruments are dual: in this stylized environment, <span class="math inline">\(\tau^{*} = t^{*}\)</span> and the same outputs arise. Cap-and-trade has the additional virtue of fixing the <em>total</em> quantity of pollution (useful when the regulator cares about an absolute pollution ceiling), while the Pigouvian tax fixes the <em>price</em> of pollution (useful when there is uncertainty about quantities).</p>
<hr>
</section>
</section>
<section id="problem-3-coase-theorem" class="level2">
<h2 class="anchored" data-anchor-id="problem-3-coase-theorem">Problem 3: Coase Theorem</h2>
<section id="part-a-total-surplus" class="level3">
<h3 class="anchored" data-anchor-id="part-a-total-surplus">Part (a): Total surplus</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Doctor not SP</th>
<th style="text-align: center;">Doctor SP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bakery noisy</td>
<td style="text-align: center;"><span class="math inline">\(260\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\boxed{300}\)</span></td>
</tr>
<tr class="even">
<td>Bakery quiet</td>
<td style="text-align: center;"><span class="math inline">\(280\)</span></td>
<td style="text-align: center;"><span class="math inline">\(250\)</span></td>
</tr>
</tbody>
</table>
<p>The efficient combination is <strong>bakery noisy + doctor soundproofed</strong> (total surplus <span class="math inline">\(300\)</span>). Soundproofing eliminates a <span class="math inline">\(\$70\)</span> noise damage at a cost of only <span class="math inline">\(\$30\)</span>, while letting the bakery keep its higher-profit noisy machinery.</p>
</section>
<section id="part-b-doctor-has-the-right-to-silence" class="level3">
<h3 class="anchored" data-anchor-id="part-b-doctor-has-the-right-to-silence">Part (b): Doctor has the right to silence</h3>
<p><strong>Without bargaining.</strong> The bakery is forced to be quiet. The doctor compares <span class="math inline">\(130\)</span> (no soundproofing) with <span class="math inline">\(100\)</span> (soundproofing) and chooses <strong>no soundproofing</strong>. Outcome: (quiet, no SP), with payoffs <span class="math inline">\((\pi_B, \pi_D) = (150, 130)\)</span> and total surplus <span class="math inline">\(280\)</span>.</p>
<p><strong>With bargaining.</strong> The parties move to (noisy, SP), where the doctor agrees to soundproof and the bakery pays the doctor <span class="math inline">\(X\)</span> for permission to be noisy. Joint surplus rises by <span class="math inline">\(20\)</span>.</p>
<ul>
<li>Bakery accepts if <span class="math inline">\(200 - X \geq 150 \Longrightarrow X \leq 50\)</span></li>
<li>Doctor accepts if <span class="math inline">\(100 + X \geq 130 \Longrightarrow X \geq 30\)</span></li>
</ul>
<p><span class="math display">\[\boxed{30 \leq X \leq 50}\]</span></p>
</section>
<section id="part-c-bakery-has-the-right-to-be-noisy" class="level3">
<h3 class="anchored" data-anchor-id="part-c-bakery-has-the-right-to-be-noisy">Part (c): Bakery has the right to be noisy</h3>
<p><strong>Without bargaining.</strong> The bakery chooses to be noisy. The doctor compares <span class="math inline">\(60\)</span> (no soundproofing) with <span class="math inline">\(100\)</span> (soundproofing) and chooses to <strong>soundproof</strong>. Outcome: (noisy, SP), total surplus <span class="math inline">\(300\)</span> - already efficient. <strong>No bargaining is required.</strong></p>
<p>The doctor unilaterally adopts the efficient response because the cost of soundproofing (<span class="math inline">\(\$30\)</span>) is less than the noise damage avoided (<span class="math inline">\(\$70\)</span>).</p>
</section>
<section id="part-d-comparison-and-the-coase-theorem" class="level3">
<h3 class="anchored" data-anchor-id="part-d-comparison-and-the-coase-theorem">Part (d): Comparison and the Coase theorem</h3>
<p>In both regimes, the efficient outcome (noisy, SP) is reached with frictionless bargaining. <strong>The assignment of property rights does not affect efficiency, only the distribution of payoffs:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Regime</th>
<th style="text-align: center;"><span class="math inline">\(\pi_B\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\pi_D\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Doctor’s right (bargained, <span class="math inline">\(X = 30\)</span>)</td>
<td style="text-align: center;"><span class="math inline">\(170\)</span></td>
<td style="text-align: center;"><span class="math inline">\(130\)</span></td>
</tr>
<tr class="even">
<td>Doctor’s right (bargained, <span class="math inline">\(X = 50\)</span>)</td>
<td style="text-align: center;"><span class="math inline">\(150\)</span></td>
<td style="text-align: center;"><span class="math inline">\(150\)</span></td>
</tr>
<tr class="odd">
<td>Bakery’s right (no bargaining)</td>
<td style="text-align: center;"><span class="math inline">\(200\)</span></td>
<td style="text-align: center;"><span class="math inline">\(100\)</span></td>
</tr>
</tbody>
</table>
<p>This is the <strong>Coase theorem</strong>: with well-defined property rights and zero transaction costs, private bargaining yields an efficient allocation regardless of the initial assignment of rights.</p>
<p><strong>Why the assignment of rights still matters in practice:</strong></p>
<ul>
<li>Real bargaining has <strong>transaction costs</strong> (lawyers, time, search) that may exceed the gains from trade.</li>
<li><strong>Asymmetric information</strong> about the parties’ valuations can prevent agreement (each side may misrepresent reservation values).</li>
<li><strong>Wealth and credit constraints</strong>: if the loser cannot afford to pay the winner, the inefficient status quo persists.</li>
<li><strong>Many parties</strong> (multiple residents, multiple polluters) make Coasian bargaining infeasible due to free-riding and coordination costs.</li>
<li><strong>Distributional / equity</strong> considerations: even if efficient, society may prefer one assignment over another.</li>
</ul>
<hr>
</section>
</section>
<section id="problem-4-public-good-provision" class="level2">
<h2 class="anchored" data-anchor-id="problem-4-public-good-provision">Problem 4: Public Good Provision</h2>
<section id="part-a-best-response-and-nash-equilibrium" class="level3">
<h3 class="anchored" data-anchor-id="part-a-best-response-and-nash-equilibrium">Part (a): Best response and Nash equilibrium</h3>
<p>Person <span class="math inline">\(i\)</span> chooses <span class="math inline">\(g_i\)</span> to maximize</p>
<p><span class="math display">\[U_i = (Y_i - g_i)(g_i + g_{-i}) = (60 - g_i)(g_i + g_{-i})\]</span></p>
<p>The FOC is <span class="math inline">\(-(g_i + g_{-i}) + (60 - g_i) = 0\)</span>, giving</p>
<p><span class="math display">\[\boxed{g_i^{*}(g_{-i}) = 30 - \frac{g_{-i}}{2}}\]</span></p>
<p>In a symmetric Nash equilibrium <span class="math inline">\(g_1 = g_2 = g_3 = g\)</span> and <span class="math inline">\(g_{-i} = 2g\)</span>:</p>
<p><span class="math display">\[g = 30 - g \;\;\Longrightarrow\;\; g_i^{*} = 15\]</span></p>
<p><span class="math display">\[\boxed{G^{*} = 45, \quad x_i^{*} = 45}\]</span></p>
</section>
<section id="part-b-social-optimum" class="level3">
<h3 class="anchored" data-anchor-id="part-b-social-optimum">Part (b): Social optimum</h3>
<p>Total welfare <span class="math inline">\(\sum_i x_i G = X G\)</span>, with <span class="math inline">\(X = \sum_i x_i\)</span> and the resource constraint <span class="math inline">\(X + G = 180\)</span>. Substituting,</p>
<p><span class="math display">\[\max_G \; G(180 - G) \;\;\Longrightarrow\;\; G^{**} = 90\]</span></p>
<p>The equal allocation gives <span class="math inline">\(X^{**} = 90\)</span> and</p>
<p><span class="math display">\[\boxed{x_i^{**} = 30, \quad G^{**} = 90}\]</span></p>
</section>
<section id="part-c-samuelson-and-the-free-rider-gap" class="level3">
<h3 class="anchored" data-anchor-id="part-c-samuelson-and-the-free-rider-gap">Part (c): Samuelson and the free-rider gap</h3>
<p>For <span class="math inline">\(U_i = x_i G\)</span>, <span class="math inline">\(MRS_i = (\partial U_i/\partial G)/(\partial U_i/\partial x_i) = x_i / G\)</span>.</p>
<ul>
<li><strong>Nash:</strong> <span class="math inline">\(MRS_i = 45/45 = 1\)</span> for each <span class="math inline">\(i\)</span>. Each person privately equates <span class="math inline">\(MRS_i\)</span> to the price of the public good, but <span class="math inline">\(\sum_i MRS_i = 3\)</span> - so collectively they massively under-provide.</li>
<li><strong>Social optimum:</strong> <span class="math inline">\(MRS_i = 30/90 = 1/3\)</span> for each <span class="math inline">\(i\)</span>, and <span class="math inline">\(\sum_i MRS_i = 1\)</span>. This is the <strong>Samuelson condition</strong> <span class="math inline">\(\sum_i MRS_i = 1\)</span> (the relative price of the public good in terms of the private good). <span class="math inline">\(\checkmark\)</span></li>
</ul>
<p><span class="math display">\[\boxed{\frac{G^{*}}{G^{**}} = \frac{45}{90} = \frac{1}{2}}\]</span></p>
<p><strong>Generalizing.</strong> With <span class="math inline">\(N\)</span> symmetric contributors, the symmetric Nash satisfies <span class="math inline">\(g_i^{*} = (60 - (N-1) g_i^{*})/2\)</span>, giving <span class="math inline">\(g_i^{*} = 60/(N+1)\)</span> and <span class="math inline">\(G^{*} = 60 N/(N+1)\)</span>. The social optimum gives <span class="math inline">\(G^{**} = NY/2 = 30 N\)</span>. So</p>
<p><span class="math display">\[\frac{G^{*}}{G^{**}} = \frac{2}{N+1}\]</span></p>
<p>As <span class="math inline">\(N \to \infty\)</span>, this ratio <span class="math inline">\(\to 0\)</span>. The free-rider problem becomes overwhelming as the number of contributors grows.</p>
</section>
<section id="part-d-pigouvian-style-subsidy" class="level3">
<h3 class="anchored" data-anchor-id="part-d-pigouvian-style-subsidy">Part (d): Pigouvian-style subsidy</h3>
<p>With subsidy rate <span class="math inline">\(s\)</span>, the consumer’s budget is <span class="math inline">\(x_i = 60 - (1-s) g_i\)</span> and</p>
<p><span class="math display">\[U_i = (60 - (1-s) g_i)(g_i + g_{-i})\]</span></p>
<p>FOC: <span class="math inline">\(-(1-s)(g_i + g_{-i}) + (60 - (1-s) g_i) = 0\)</span>, giving <span class="math inline">\(60 = (1-s)(2 g_i + g_{-i})\)</span>.</p>
<p>Symmetric: <span class="math inline">\(60 = (1-s)\cdot 4 g \Longrightarrow g = 15/(1 - s)\)</span> and <span class="math inline">\(G = 45/(1-s)\)</span>.</p>
<p>Setting <span class="math inline">\(G = G^{**} = 90\)</span>:</p>
<p><span class="math display">\[\frac{45}{1 - s} = 90 \;\;\Longrightarrow\;\; 1 - s = \frac{1}{2} \;\;\Longrightarrow\;\; \boxed{s^{*} = \frac{1}{2}}\]</span></p>
<p>The government covers half the cost of each contribution, exactly internalizing the externality each contributor imposes on the other two. (More generally, for <span class="math inline">\(N\)</span> contributors, <span class="math inline">\(s^{*} = (N-1)/(N+1)\)</span>.)</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>2026 Div Bhagia | <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0 License</a> |Made with <a href="https://quarto.org/">Quarto</a></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>